- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-0220d79f3f480ecf5
    subnet_id: subnet-04d4f1ebfd040d45e
    sg_id: sg-05ff4bd44c0bc3ba5 
    zone_id: "Z08339141ZNV0KWJ5D2UQ" 
    domain_name: "vdavin.online"
    key_name: "vdavin-pem"
    # we can pass instances through command line using -e
    instances: 
    - mongodb
    # - redis
    # - mysql
    # - rabbitmq
  tasks:
  - name: create ec2 instance   # pip3.9 install botocore boto3
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      # key_name: "{{ key_name }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: print public_ip
    ansible.builtin.debug: 
      msg: "{{ item.instances[0].public_ip_address }}"
    loop: "{{ ec2_output.results }}"
    register: ec2_output1

    - name: print the ec2_output1
    ansible.builtin.debug:
      msg: "{{ ec2_output1 }}

  - name: print private_ip
    ansible.builtin.debug: 
      msg: "{{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_output.results }}"

  - name: create route53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}.{{ domain_name }}" # mongodb.daws86s.fun
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"

  # we are creating one record with public only for frontend
  - name: create route53 record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ domain_name }}" # daws86s.fun
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true
    when: item.item == "frontend"
    loop: "{{ ec2_output.results }}"